# Generated by Django 3.2.7 on 2021-09-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questoin_text',
            new_name='question_text',
        ),
    ]
