# Generated by Django 3.2.7 on 2021-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_questoin_text_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
